#!/bin/sh
## This is a rcS file for udev startup,dev nodes making,and other init.
## Created by hyyeah@8.12.2008

# If /sbin/udevstart and /sbin/udev both exist,
# using udev and our rules to create device nodes.
if [ -e /sbin/udevstart -a -e /sbin/udevd ] ; then
	
	# Mount tmpfs on /dev, so device nodes created
	# by udev should exist in ram.(tmpfs based on ram)
	/bin/mount -t tmpfs udev /dev >/dev/null 2>&1
	# Error check.
	if [ $? -ne 0 ]; then
		echo "Mounting udev failed"
	fi

	# If /dev/pts directory doesn't exist,
	# we create it.
	if [ ! -e /dev/pts ]; then
		/bin/mkdir -p /dev/pts
	fi
	
	# Mount devpts on /dev/pts, used for
	# pseudo terminal, such as telnet.
	/bin/mount -t devpts devpts /dev/pts >/dev/null 2>&1
	# Error check
	if [ $? -ne 0 ]; then
		echo "Mounting devpts failed"
	fi
	
	if [ -e /proc/sys/kernel/hotplug ] ; then
		echo "" > /proc/sys/kernel/hotplug
	fi

	# The core of udev startup.
	echo -n "Starting udev:      "
	
	# Runing udevd daemon, the return of this command
	# saved in variable $ret.
	/sbin/udevd -d >/dev/null 2>&1; ret=$?
	
	# Running udevstart, the return saved in $?.
	/sbin/udevstart >/dev/null 2>&1
	
	# If udevstart and udevd both return 0,
	# udev starts ok, otherwise failed.
	if [ $? -eq 0 -a $ret -eq 0 ]; then
		echo "[ OK ]"
	else
		echo "[ FAILED ]"
	fi

# If /sbin/udevstart or /sbin/udev doesn't exist,
# using default device nodes created by wrlinux workbench.
else
	 echo "No udev support, use default devfs"
fi